GET http://localhost:80/api/item?id=99
Accept: application/json

###
### register
POST localhost:8080/register

{
    "email": "user.some123@gmail.com",
    "password": "password123"
}

### login
POST localhost:8080/login

{
    "email": "user.some123@gmail.com",
    "password": "password123"
}

### get user
GET localhost:8080/users/62
cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU5MDU3NjUsInN1YiI6IjY0In0.zEzWKE22OH3TIJ8kY6gIuSp6ijwHBYnetd2E4CE7AcM

### refresh token
POST localhost:8080/refresh
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjUxMzQxODYsInN1YiI6IjAifQ.dUyXIffIaxNI1Bb1sZu9zdou9Tt5wzWjGNZmNlu4a8A

### verify token
POST localhost:8080/verify
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjUxMzU2NDQsInN1YiI6IjAifQ.uj7PDfgL_zL4l-Xp4RWPktnpT0uDHojDIfEnDLiTReQ